
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay

stages:
  - build
  - test

.anchors:
  - &inject-gopath
      cd $GOPATH/src &&
      mkdir -p github.com/${CI_PROJECT_NAMESPACE} &&
      cd github.com/${CI_PROJECT_NAMESPACE} &&
      ln -s ${CI_PROJECT_DIR}
      && cd ${CI_PROJECT_NAME}

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - docker build -f Dockerfile -t kierachell/practice .
  script:
    - docker run kierachell/practice

test_python:
  image: python:3.6.6
  stage: test
  tags:
    - docker
  before_script:
    - cd ./python
    - pip install -r requirements.txt
  script:
    - python -m unittest discover -s test

test_go:
  image: golang:1.11
  stage: test
  tags:
    - docker
  before_script:
    - *inject-gopath
  script:
    - go test -v -bench=. -benchmem ./...
