
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay
  PACKAGE_PATH: /go/src/github.com/kierachell/practice/

stages:
  - build
  - test

.anchors:
  - &inject-gopath
      mkdir -p $(dirname ${PACKAGE_PATH})
      && ln -s ${CI_PROJECT_DIR} ${PACKAGE_PATH}
      && cd ${PACKAGE_PATH}

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - docker build -f Dockerfile -t kierachell/practice .
  script:
    - docker run kierachell/practice

test:
  image: golang:1.11
  stage: test
  tags:
    - docker
  before_script:
    - *inject-gopath
  script:
    - go test -v -bench=.
