
variables:
  DOCKER_HOST: 'tcp://docker:2375'
  DOCKER_DRIVER: 'overlay'
  GO111MODULE: 'on'

stages:
  - build
  - test

.anchors:
  - &inject-gopath
      cd $GOPATH/src &&
      mkdir -p github.com/${CI_PROJECT_NAMESPACE} &&
      cd github.com/${CI_PROJECT_NAMESPACE} &&
      ln -s ${CI_PROJECT_DIR} &&
      cd ${CI_PROJECT_NAME}

build_docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - docker build -f Dockerfile -t kierachell/practice .
  script:
    - docker run kierachell/practice

build_proto:
  stage: build
  image: golang:1.11
  tags:
    - docker
  before_script:
    - *inject-gopath
  script:
    - GO111MODULE="off" go get -u github.com/golang/protobuf/protoc-gen-go
    - protoc --go_out=. data/*.proto

test_python:
  stage: test
  image: python:3.7.0
  tags:
    - docker
  before_script:
    - cd ./python
    - pip install -r requirements.txt
  script:
    - python -m unittest discover -s test

test_go:
  stage: test
  image: golang:1.11
  tags:
    - docker
  before_script:
    - *inject-gopath
  script:
    - go mod download
    - go test -v -bench=. -benchmem ./...
