
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay

stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - docker build -f Dockerfile -t kierachell/practice .
  script:
    - docker run kierachell/practice

test:
  image: golang:1.11
  stage: test
  tags:
    - docker
  before_script:
    - mkdir -p /go/src/github.com/kierachell/practice/
    - cp -r $CI_PROJECT_DIR /go/src/github.com/kierachell/practice/
  script:
    - cd /go/src/github.com/kierachell/practice/
    - go test -v -bench=.
