image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  before_script:
    - docker build -f Dockerfile -t kierachell/practice .
  script:
    - docker run -it kierachell/practice

test:
  stage: test
  tags:
    - docker
  script:
    - go test -v -bench=.
