// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

package data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Entry struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_c1884608313fc615, []int{0}
}
func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (dst *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(dst, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type State struct {
	CurrentTerm          uint64   `protobuf:"varint,1,opt,name=currentTerm,proto3" json:"currentTerm,omitempty"`
	VotedFor             string   `protobuf:"bytes,2,opt,name=votedFor,proto3" json:"votedFor,omitempty"`
	Log                  []*Entry `protobuf:"bytes,3,rep,name=log,proto3" json:"log,omitempty"`
	CommitIndex          uint64   `protobuf:"varint,4,opt,name=commitIndex,proto3" json:"commitIndex,omitempty"`
	LastApplied          uint64   `protobuf:"varint,5,opt,name=lastApplied,proto3" json:"lastApplied,omitempty"`
	NextIndex            []uint64 `protobuf:"varint,6,rep,packed,name=nextIndex,proto3" json:"nextIndex,omitempty"`
	MatchIndex           []uint64 `protobuf:"varint,7,rep,packed,name=matchIndex,proto3" json:"matchIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_c1884608313fc615, []int{1}
}
func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (dst *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(dst, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetCurrentTerm() uint64 {
	if m != nil {
		return m.CurrentTerm
	}
	return 0
}

func (m *State) GetVotedFor() string {
	if m != nil {
		return m.VotedFor
	}
	return ""
}

func (m *State) GetLog() []*Entry {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *State) GetCommitIndex() uint64 {
	if m != nil {
		return m.CommitIndex
	}
	return 0
}

func (m *State) GetLastApplied() uint64 {
	if m != nil {
		return m.LastApplied
	}
	return 0
}

func (m *State) GetNextIndex() []uint64 {
	if m != nil {
		return m.NextIndex
	}
	return nil
}

func (m *State) GetMatchIndex() []uint64 {
	if m != nil {
		return m.MatchIndex
	}
	return nil
}

type AppendEntryRequest struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId             string   `protobuf:"bytes,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	PrevLogEntry         uint64   `protobuf:"varint,3,opt,name=prevLogEntry,proto3" json:"prevLogEntry,omitempty"`
	PrevLogTerm          uint64   `protobuf:"varint,4,opt,name=prevLogTerm,proto3" json:"prevLogTerm,omitempty"`
	Entries              []*Entry `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit         uint64   `protobuf:"varint,6,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntryRequest) Reset()         { *m = AppendEntryRequest{} }
func (m *AppendEntryRequest) String() string { return proto.CompactTextString(m) }
func (*AppendEntryRequest) ProtoMessage()    {}
func (*AppendEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_c1884608313fc615, []int{2}
}
func (m *AppendEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntryRequest.Unmarshal(m, b)
}
func (m *AppendEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntryRequest.Marshal(b, m, deterministic)
}
func (dst *AppendEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntryRequest.Merge(dst, src)
}
func (m *AppendEntryRequest) XXX_Size() int {
	return xxx_messageInfo_AppendEntryRequest.Size(m)
}
func (m *AppendEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntryRequest proto.InternalMessageInfo

func (m *AppendEntryRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntryRequest) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *AppendEntryRequest) GetPrevLogEntry() uint64 {
	if m != nil {
		return m.PrevLogEntry
	}
	return 0
}

func (m *AppendEntryRequest) GetPrevLogTerm() uint64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntryRequest) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AppendEntryRequest) GetLeaderCommit() uint64 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

type AppendEntryResponse struct {
	CommitIndex          uint64   `protobuf:"varint,1,opt,name=commitIndex,proto3" json:"commitIndex,omitempty"`
	Added                bool     `protobuf:"varint,2,opt,name=added,proto3" json:"added,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntryResponse) Reset()         { *m = AppendEntryResponse{} }
func (m *AppendEntryResponse) String() string { return proto.CompactTextString(m) }
func (*AppendEntryResponse) ProtoMessage()    {}
func (*AppendEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_c1884608313fc615, []int{3}
}
func (m *AppendEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntryResponse.Unmarshal(m, b)
}
func (m *AppendEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntryResponse.Marshal(b, m, deterministic)
}
func (dst *AppendEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntryResponse.Merge(dst, src)
}
func (m *AppendEntryResponse) XXX_Size() int {
	return xxx_messageInfo_AppendEntryResponse.Size(m)
}
func (m *AppendEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntryResponse proto.InternalMessageInfo

func (m *AppendEntryResponse) GetCommitIndex() uint64 {
	if m != nil {
		return m.CommitIndex
	}
	return 0
}

func (m *AppendEntryResponse) GetAdded() bool {
	if m != nil {
		return m.Added
	}
	return false
}

type RequestVoteRequest struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId          string   `protobuf:"bytes,2,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	LastLogIndex         uint64   `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LastLogTerm          uint64   `protobuf:"varint,4,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestVoteRequest) Reset()         { *m = RequestVoteRequest{} }
func (m *RequestVoteRequest) String() string { return proto.CompactTextString(m) }
func (*RequestVoteRequest) ProtoMessage()    {}
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_c1884608313fc615, []int{4}
}
func (m *RequestVoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestVoteRequest.Unmarshal(m, b)
}
func (m *RequestVoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestVoteRequest.Marshal(b, m, deterministic)
}
func (dst *RequestVoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestVoteRequest.Merge(dst, src)
}
func (m *RequestVoteRequest) XXX_Size() int {
	return xxx_messageInfo_RequestVoteRequest.Size(m)
}
func (m *RequestVoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestVoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestVoteRequest proto.InternalMessageInfo

func (m *RequestVoteRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *RequestVoteRequest) GetCandidateId() string {
	if m != nil {
		return m.CandidateId
	}
	return ""
}

func (m *RequestVoteRequest) GetLastLogIndex() uint64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *RequestVoteRequest) GetLastLogTerm() uint64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

func init() {
	proto.RegisterType((*Entry)(nil), "data.Entry")
	proto.RegisterType((*State)(nil), "data.State")
	proto.RegisterType((*AppendEntryRequest)(nil), "data.AppendEntryRequest")
	proto.RegisterType((*AppendEntryResponse)(nil), "data.AppendEntryResponse")
	proto.RegisterType((*RequestVoteRequest)(nil), "data.RequestVoteRequest")
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor_raft_c1884608313fc615) }

var fileDescriptor_raft_c1884608313fc615 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4d, 0x4e, 0xfb, 0x30,
	0x10, 0xc5, 0x95, 0x7f, 0x92, 0x7e, 0x4c, 0xff, 0x2b, 0xc3, 0xc2, 0xe2, 0x4b, 0x51, 0x24, 0xa4,
	0xae, 0xba, 0x80, 0x13, 0x54, 0x08, 0xa4, 0x4a, 0x65, 0x13, 0x10, 0x7b, 0x53, 0x0f, 0x25, 0x52,
	0x62, 0x07, 0x67, 0x5a, 0x95, 0x5b, 0x70, 0x39, 0xae, 0xc0, 0x39, 0x50, 0xec, 0xa4, 0x75, 0x5b,
	0x89, 0x9d, 0xe7, 0x37, 0xd3, 0x79, 0xf3, 0x5e, 0x03, 0x60, 0xc4, 0x1b, 0x4d, 0x2a, 0xa3, 0x49,
	0xb3, 0x48, 0x0a, 0x12, 0xe9, 0x39, 0xc4, 0xf7, 0x8a, 0xcc, 0x27, 0x63, 0x10, 0x11, 0x6e, 0x88,
	0x07, 0x49, 0x30, 0x1e, 0x66, 0xf6, 0x9d, 0xfe, 0x04, 0x10, 0x3f, 0x91, 0x20, 0x64, 0x09, 0x8c,
	0x16, 0x2b, 0x63, 0x50, 0xd1, 0x33, 0x9a, 0xd2, 0x0e, 0x45, 0x99, 0x8f, 0xd8, 0x19, 0x0c, 0xd6,
	0x9a, 0x50, 0x3e, 0x68, 0xc3, 0xff, 0xd9, 0x1d, 0xdb, 0x9a, 0x5d, 0x42, 0x58, 0xe8, 0x25, 0x0f,
	0x93, 0x70, 0x3c, 0xba, 0x19, 0x4d, 0x1a, 0xe1, 0x89, 0x55, 0xcd, 0x1a, 0x6e, 0x97, 0xeb, 0xb2,
	0xcc, 0x69, 0xa6, 0x24, 0x6e, 0x78, 0xd4, 0x2e, 0xdf, 0xa1, 0x66, 0xa2, 0x10, 0x35, 0x4d, 0xab,
	0xaa, 0xc8, 0x51, 0xf2, 0xd8, 0x4d, 0x78, 0x88, 0x5d, 0xc0, 0x50, 0xe1, 0xa6, 0xdd, 0xd0, 0x4b,
	0xc2, 0x71, 0x94, 0xed, 0x00, 0xbb, 0x02, 0x28, 0x05, 0x2d, 0xde, 0x5d, 0xbb, 0x6f, 0xdb, 0x1e,
	0x49, 0xbf, 0x03, 0x60, 0xd3, 0xaa, 0x42, 0x25, 0xdd, 0x59, 0xf8, 0xb1, 0xc2, 0x9a, 0x5c, 0x26,
	0x5b, 0xbb, 0xf6, 0xdd, 0xf8, 0x2c, 0x50, 0x48, 0x34, 0x33, 0xd9, 0xf9, 0xec, 0x6a, 0x96, 0xc2,
	0xff, 0xca, 0xe0, 0x7a, 0xae, 0x97, 0x76, 0x0d, 0x0f, 0xed, 0xef, 0xf6, 0x58, 0x63, 0xa5, 0xad,
	0x6d, 0x92, 0xad, 0x59, 0x0f, 0xb1, 0x6b, 0xe8, 0xa3, 0x22, 0x93, 0x63, 0xcd, 0xe3, 0xe3, 0xc4,
	0xba, 0x5e, 0x23, 0xe6, 0x84, 0xef, 0x6c, 0x50, 0xbc, 0xe7, 0xc4, 0x7c, 0x96, 0x3e, 0xc2, 0xc9,
	0x9e, 0xad, 0xba, 0xd2, 0xaa, 0xc6, 0xc3, 0xc0, 0x83, 0xe3, 0xc0, 0x4f, 0x21, 0x16, 0x52, 0xa2,
	0xb3, 0x38, 0xc8, 0x5c, 0x91, 0x7e, 0x05, 0xc0, 0xda, 0x6c, 0x5e, 0x34, 0xe1, 0x5f, 0x31, 0x35,
	0x12, 0x42, 0xc9, 0x5c, 0x0a, 0xc2, 0x6d, 0x52, 0x3e, 0xb2, 0xf7, 0x8b, 0x9a, 0xe6, 0x7a, 0xe9,
	0xae, 0x68, 0xc3, 0xf2, 0x59, 0xf7, 0xbf, 0x1f, 0x84, 0xe5, 0xa1, 0xd7, 0x9e, 0xfd, 0x98, 0x6f,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x14, 0x73, 0xa5, 0xb1, 0xda, 0x02, 0x00, 0x00,
}
