// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data/chord.proto

package data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_chord_a0fba4578b65fbfd, []int{0}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type InsertRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertRequest) Reset()         { *m = InsertRequest{} }
func (m *InsertRequest) String() string { return proto.CompactTextString(m) }
func (*InsertRequest) ProtoMessage()    {}
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chord_a0fba4578b65fbfd, []int{1}
}
func (m *InsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertRequest.Unmarshal(m, b)
}
func (m *InsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertRequest.Marshal(b, m, deterministic)
}
func (dst *InsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertRequest.Merge(dst, src)
}
func (m *InsertRequest) XXX_Size() int {
	return xxx_messageInfo_InsertRequest.Size(m)
}
func (m *InsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertRequest proto.InternalMessageInfo

func (m *InsertRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *InsertRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type InsertResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertResponse) Reset()         { *m = InsertResponse{} }
func (m *InsertResponse) String() string { return proto.CompactTextString(m) }
func (*InsertResponse) ProtoMessage()    {}
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chord_a0fba4578b65fbfd, []int{2}
}
func (m *InsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertResponse.Unmarshal(m, b)
}
func (m *InsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertResponse.Marshal(b, m, deterministic)
}
func (dst *InsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertResponse.Merge(dst, src)
}
func (m *InsertResponse) XXX_Size() int {
	return xxx_messageInfo_InsertResponse.Size(m)
}
func (m *InsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertResponse proto.InternalMessageInfo

func (m *InsertResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type JoinRequest struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chord_a0fba4578b65fbfd, []int{3}
}
func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (dst *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(dst, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type JoinResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chord_a0fba4578b65fbfd, []int{4}
}
func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (dst *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(dst, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type LookupRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Origin               string   `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupRequest) Reset()         { *m = LookupRequest{} }
func (m *LookupRequest) String() string { return proto.CompactTextString(m) }
func (*LookupRequest) ProtoMessage()    {}
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_chord_a0fba4578b65fbfd, []int{5}
}
func (m *LookupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupRequest.Unmarshal(m, b)
}
func (m *LookupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupRequest.Marshal(b, m, deterministic)
}
func (dst *LookupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupRequest.Merge(dst, src)
}
func (m *LookupRequest) XXX_Size() int {
	return xxx_messageInfo_LookupRequest.Size(m)
}
func (m *LookupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookupRequest proto.InternalMessageInfo

func (m *LookupRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *LookupRequest) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

type LookupResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupResponse) Reset()         { *m = LookupResponse{} }
func (m *LookupResponse) String() string { return proto.CompactTextString(m) }
func (*LookupResponse) ProtoMessage()    {}
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chord_a0fba4578b65fbfd, []int{6}
}
func (m *LookupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupResponse.Unmarshal(m, b)
}
func (m *LookupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupResponse.Marshal(b, m, deterministic)
}
func (dst *LookupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupResponse.Merge(dst, src)
}
func (m *LookupResponse) XXX_Size() int {
	return xxx_messageInfo_LookupResponse.Size(m)
}
func (m *LookupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookupResponse proto.InternalMessageInfo

func (m *LookupResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *LookupResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Error)(nil), "data.Error")
	proto.RegisterType((*InsertRequest)(nil), "data.InsertRequest")
	proto.RegisterType((*InsertResponse)(nil), "data.InsertResponse")
	proto.RegisterType((*JoinRequest)(nil), "data.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "data.JoinResponse")
	proto.RegisterType((*LookupRequest)(nil), "data.LookupRequest")
	proto.RegisterType((*LookupResponse)(nil), "data.LookupResponse")
}

func init() { proto.RegisterFile("data/chord.proto", fileDescriptor_chord_a0fba4578b65fbfd) }

var fileDescriptor_chord_a0fba4578b65fbfd = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x0d, 0x4a, 0x9b, 0x30, 0x08, 0xc1, 0x95, 0x10, 0x52, 0x2e, 0xba, 0x89, 0x89, 0x07, 0x5d,
	0x22, 0x3d, 0x18, 0xcf, 0x86, 0x03, 0x86, 0x78, 0xe0, 0x1f, 0x14, 0x3b, 0x62, 0x03, 0x76, 0xea,
	0x76, 0x4b, 0xe4, 0x6f, 0xfa, 0x8b, 0xcc, 0x7e, 0x25, 0xad, 0xd1, 0x84, 0xdb, 0xce, 0x9b, 0x37,
	0xfb, 0xf6, 0xbd, 0x1d, 0x18, 0xa4, 0x89, 0x4a, 0xa6, 0xaf, 0xef, 0x24, 0x53, 0x51, 0x48, 0x52,
	0xc4, 0xda, 0x1a, 0x89, 0x26, 0x1b, 0xa2, 0xcd, 0x0e, 0xa7, 0x06, 0x5b, 0x57, 0x6f, 0x53, 0xfc,
	0x28, 0xd4, 0xc1, 0x52, 0xf8, 0x04, 0x82, 0xb9, 0x94, 0x24, 0x19, 0x83, 0xb6, 0xc2, 0x2f, 0x35,
	0x6e, 0x5d, 0xb6, 0x6e, 0x3a, 0x2b, 0x73, 0xe6, 0x0f, 0xd0, 0x5b, 0xe4, 0x25, 0x4a, 0xb5, 0xc2,
	0xcf, 0x0a, 0x4b, 0xc5, 0x06, 0x70, 0xba, 0xc5, 0x83, 0xe3, 0xe8, 0x23, 0x1b, 0x42, 0xb0, 0x4f,
	0x76, 0x15, 0x8e, 0x4f, 0x0c, 0x66, 0x0b, 0x1e, 0x43, 0xdf, 0x0f, 0x96, 0x05, 0xe5, 0x25, 0xb2,
	0x2b, 0x08, 0x50, 0xeb, 0x98, 0xd9, 0xee, 0xac, 0x2b, 0xf4, 0xd3, 0x84, 0x91, 0x5e, 0xd9, 0x0e,
	0xbf, 0x86, 0xee, 0x33, 0x65, 0xb9, 0xd7, 0x1a, 0x41, 0x98, 0x53, 0x8a, 0x8b, 0xd4, 0xc9, 0xb9,
	0x8a, 0xdf, 0xc3, 0x99, 0xa5, 0x1d, 0x7f, 0xf3, 0x23, 0xf4, 0x96, 0x44, 0xdb, 0xaa, 0xf8, 0xdf,
	0xc7, 0x08, 0x42, 0x92, 0xd9, 0x26, 0xcb, 0x9d, 0x11, 0x57, 0xf1, 0x05, 0xf4, 0xfd, 0xe8, 0xd1,
	0x7a, 0x7f, 0x87, 0x32, 0xfb, 0x6e, 0x41, 0xe7, 0x49, 0xff, 0xce, 0x0b, 0xa5, 0xc8, 0x62, 0x08,
	0x6d, 0x44, 0xec, 0xc2, 0xde, 0xd0, 0x48, 0x3a, 0x1a, 0x36, 0x41, 0xa7, 0x7d, 0x07, 0x6d, 0xed,
	0x9d, 0x9d, 0xdb, 0x6e, 0x2d, 0xae, 0x88, 0xd5, 0x21, 0x47, 0x8f, 0x21, 0xb4, 0x8f, 0xf7, 0x1a,
	0x8d, 0x14, 0xbc, 0xc6, 0x2f, 0x7f, 0xb7, 0x10, 0x2c, 0x31, 0xd9, 0x23, 0x1b, 0x09, 0xbb, 0x38,
	0xc2, 0x2f, 0x8e, 0x98, 0xeb, 0xc5, 0x89, 0xea, 0x8e, 0xd7, 0xa1, 0x69, 0xc6, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xf2, 0xf6, 0x42, 0x4e, 0x7d, 0x02, 0x00, 0x00,
}
