// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data/raft.proto

package data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Entry struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_e8a4828af77f27d1, []int{0}
}
func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (dst *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(dst, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type State struct {
	CurrentTerm          uint64   `protobuf:"varint,1,opt,name=currentTerm,proto3" json:"currentTerm,omitempty"`
	VotedFor             string   `protobuf:"bytes,2,opt,name=votedFor,proto3" json:"votedFor,omitempty"`
	Log                  []*Entry `protobuf:"bytes,3,rep,name=log,proto3" json:"log,omitempty"`
	CommitIndex          uint64   `protobuf:"varint,4,opt,name=commitIndex,proto3" json:"commitIndex,omitempty"`
	LastApplied          uint64   `protobuf:"varint,5,opt,name=lastApplied,proto3" json:"lastApplied,omitempty"`
	NextIndex            []uint64 `protobuf:"varint,6,rep,packed,name=nextIndex,proto3" json:"nextIndex,omitempty"`
	MatchIndex           []uint64 `protobuf:"varint,7,rep,packed,name=matchIndex,proto3" json:"matchIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_e8a4828af77f27d1, []int{1}
}
func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (dst *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(dst, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetCurrentTerm() uint64 {
	if m != nil {
		return m.CurrentTerm
	}
	return 0
}

func (m *State) GetVotedFor() string {
	if m != nil {
		return m.VotedFor
	}
	return ""
}

func (m *State) GetLog() []*Entry {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *State) GetCommitIndex() uint64 {
	if m != nil {
		return m.CommitIndex
	}
	return 0
}

func (m *State) GetLastApplied() uint64 {
	if m != nil {
		return m.LastApplied
	}
	return 0
}

func (m *State) GetNextIndex() []uint64 {
	if m != nil {
		return m.NextIndex
	}
	return nil
}

func (m *State) GetMatchIndex() []uint64 {
	if m != nil {
		return m.MatchIndex
	}
	return nil
}

type AppendEntryRequest struct {
	Term                 uint64   `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId             string   `protobuf:"bytes,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	PrevLogEntry         uint64   `protobuf:"varint,3,opt,name=prevLogEntry,proto3" json:"prevLogEntry,omitempty"`
	PrevLogTerm          uint64   `protobuf:"varint,4,opt,name=prevLogTerm,proto3" json:"prevLogTerm,omitempty"`
	Entries              []*Entry `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit         uint64   `protobuf:"varint,6,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendEntryRequest) Reset()         { *m = AppendEntryRequest{} }
func (m *AppendEntryRequest) String() string { return proto.CompactTextString(m) }
func (*AppendEntryRequest) ProtoMessage()    {}
func (*AppendEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_raft_e8a4828af77f27d1, []int{2}
}
func (m *AppendEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendEntryRequest.Unmarshal(m, b)
}
func (m *AppendEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendEntryRequest.Marshal(b, m, deterministic)
}
func (dst *AppendEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendEntryRequest.Merge(dst, src)
}
func (m *AppendEntryRequest) XXX_Size() int {
	return xxx_messageInfo_AppendEntryRequest.Size(m)
}
func (m *AppendEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendEntryRequest proto.InternalMessageInfo

func (m *AppendEntryRequest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntryRequest) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *AppendEntryRequest) GetPrevLogEntry() uint64 {
	if m != nil {
		return m.PrevLogEntry
	}
	return 0
}

func (m *AppendEntryRequest) GetPrevLogTerm() uint64 {
	if m != nil {
		return m.PrevLogTerm
	}
	return 0
}

func (m *AppendEntryRequest) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AppendEntryRequest) GetLeaderCommit() uint64 {
	if m != nil {
		return m.LeaderCommit
	}
	return 0
}

func init() {
	proto.RegisterType((*Entry)(nil), "data.Entry")
	proto.RegisterType((*State)(nil), "data.State")
	proto.RegisterType((*AppendEntryRequest)(nil), "data.AppendEntryRequest")
}

func init() { proto.RegisterFile("data/raft.proto", fileDescriptor_raft_e8a4828af77f27d1) }

var fileDescriptor_raft_e8a4828af77f27d1 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xdf, 0x4a, 0xf3, 0x40,
	0x10, 0xc5, 0xc9, 0x97, 0xa4, 0xfd, 0x3a, 0x15, 0x84, 0xbd, 0x5a, 0xfc, 0x47, 0x08, 0x08, 0xbd,
	0xaa, 0xa0, 0x4f, 0x50, 0x44, 0xa1, 0xe0, 0x55, 0xf4, 0x05, 0xd6, 0xee, 0x58, 0x0b, 0xc9, 0xee,
	0xba, 0x9d, 0x96, 0xf8, 0xa0, 0xbe, 0x82, 0xcf, 0x21, 0x3b, 0x9b, 0xb4, 0x11, 0xef, 0x66, 0x7e,
	0x33, 0x39, 0x27, 0x67, 0x16, 0x4e, 0xb5, 0x22, 0x75, 0xe3, 0xd5, 0x1b, 0xcd, 0x9d, 0xb7, 0x64,
	0x45, 0x16, 0x40, 0x79, 0x0e, 0xf9, 0x83, 0x21, 0xff, 0x29, 0x04, 0x64, 0x84, 0x2d, 0xc9, 0xa4,
	0x48, 0x66, 0x93, 0x8a, 0xeb, 0xf2, 0x3b, 0x81, 0xfc, 0x99, 0x14, 0xa1, 0x28, 0x60, 0xba, 0xda,
	0x79, 0x8f, 0x86, 0x5e, 0xd0, 0x37, 0xbc, 0x94, 0x55, 0x43, 0x24, 0xce, 0xe0, 0xff, 0xde, 0x12,
	0xea, 0x47, 0xeb, 0xe5, 0x3f, 0xd6, 0x38, 0xf4, 0xe2, 0x12, 0xd2, 0xda, 0xae, 0x65, 0x5a, 0xa4,
	0xb3, 0xe9, 0xed, 0x74, 0x1e, 0x8c, 0xe7, 0xec, 0x5a, 0x05, 0xce, 0xe2, 0xb6, 0x69, 0x36, 0xb4,
	0x34, 0x1a, 0x5b, 0x99, 0x75, 0xe2, 0x47, 0x14, 0x36, 0x6a, 0xb5, 0xa5, 0x85, 0x73, 0xf5, 0x06,
	0xb5, 0xcc, 0xe3, 0xc6, 0x00, 0x89, 0x0b, 0x98, 0x18, 0x6c, 0x3b, 0x85, 0x51, 0x91, 0xce, 0xb2,
	0xea, 0x08, 0xc4, 0x15, 0x40, 0xa3, 0x68, 0xf5, 0x1e, 0xc7, 0x63, 0x1e, 0x0f, 0x48, 0xf9, 0x95,
	0x80, 0x58, 0x38, 0x87, 0x46, 0xc7, 0xdf, 0xc2, 0x8f, 0x1d, 0x6e, 0x29, 0xde, 0xe4, 0x10, 0x97,
	0xeb, 0x90, 0xb3, 0x46, 0xa5, 0xd1, 0x2f, 0x75, 0x9f, 0xb3, 0xef, 0x45, 0x09, 0x27, 0xce, 0xe3,
	0xfe, 0xc9, 0xae, 0x59, 0x46, 0xa6, 0xfc, 0xdd, 0x2f, 0x16, 0xa2, 0x74, 0x3d, 0x5f, 0xb2, 0x0b,
	0x3b, 0x40, 0xe2, 0x1a, 0xc6, 0x68, 0xc8, 0x6f, 0x70, 0x2b, 0xf3, 0xbf, 0x17, 0xeb, 0x67, 0xc1,
	0x2c, 0x1a, 0xdf, 0xf3, 0xa1, 0xe4, 0x28, 0x9a, 0x0d, 0xd9, 0xeb, 0x88, 0x9f, 0xfa, 0xee, 0x27,
	0x00, 0x00, 0xff, 0xff, 0x74, 0xb0, 0x09, 0x20, 0xfd, 0x01, 0x00, 0x00,
}
